### ISSUE TITLE
Still active -- Trying to wrap my head around the language.

### ISSUE THREAD

**Issue by novusabeo** [sl236/Piet#4]
Hi, 

really interested in this project and was hoping to get a little more information on how to write a program. 

Read through the documentation at https://www.toothycat.net/wiki/wiki.pl?MoonShadow/Piet

But having a little trouble understanding some directives or code pieces. Any way you would be willing to elaborate some more on some of it?

Not totally understanding what the : does in 0:bz.1f.pop
Also what is the 1f about?

<strong>
macro # print - pop string from stack and print it
    dup 
 0: bz.1f.pop 
    2 1 roll 
    out 
    1 sub 
    br.0b.dup 
 1: 
print def

macro print 10 out println def
    
# -----------------------------------------

1
0:
dup 15 mod bz._track_3
dup 3 mod bz._track_1
dup 5 mod bz._track_2
dup outn 10 out

_track_0:
1 add dup 100 brle.0b

halt

.track #1
"Fizz" println br._track_0
.track #2
"Buzz" println br._track_0
.track #3
"FizzBuzz" println br._track_0

</strong>

I don't know, I know how Piet itself works when reading an image but trying to understand it from this side also so I could write something to, let's say, ask for two input numbers and add them and then print the output.

**Comment by novusabeo** [comment]
Actually, I think my problem is with the compiler.
Getting a /bin/perl: bad interpreter: No such file or directory
when i run ./piet-compiler on anything using the code provided in the readme. 

On MacOS
I have perl installed, not sure??

**Comment by sl236** [comment]
Hi,

0:
1:
etc are labels which mark positions in your code for branches to refer to.
So, b.1 will generate a branch to label 1, i.e. execution will move to the
line starting with 1: in your source.

Now, the assembler provides macros, as many assemblers do. Macros are
named pieces of text: all text between the keyword "macro" and the
"<identifier> def" expression just gets dumbly pasted wherever
<identifier> occurs in the source thereafter.

We'd like to be able to define macros that contain conditionals and loops.
However, if these macros are used multiple times in the program, the same
labels will occur multiple times in the program, because everywhere you
use a macro the macro's text is just dumbly pasted in.

That's what the 'f' and 'b' is for. By default, the assembler will search
backwards from the branch and go to the nearest matching label. This is
generally what you want for loops: a branch that goes back to the loop
start. But you don't normally want this for conditional statements: you
want to generate a branch that skips forward over some code depending on
the condition. So you can add an 'f' or 'b' to the label in the branch
instruction to explicitly tell the assembler to search forwards or backwards as required.

Compare what a real assembler does for this stuff:
ftp://ftp.gnu.org/old-gnu/Manuals/gas/html_node/as_48.html#SEC48
the section under "Local symbol names" is basically what I've just
described above.

Finally, Piet has the peculiarity that during the flow of execution the
interpreter is actually traversing pixels in an image; in order to
generate a branch, we must actually draw a line of pixels in the image
connecting the source and the destination. There is room on this line for
Piet instructions, which will be performed as the interpreter follows the
line if the branch is taken. The assembler provides a way for you to
specify instructions to go here.

So,
0: bz.1f.pop

means "branch if zero to the next line prefixed with 1: in the source,
searching forwards from this location; execute the 'pop' instruction while
branching if the branch is taken; and also label this line with the label 0 so branches elsewhere can refer to it".

(FWIW this actually feels very similar to using the GNU assembler to write
code for an architecture that has exposed branch delay slots like MIPS)

**Comment by novusabeo** [comment]
So in the case of `macro # print - pop string from stack and print it dup 0: bz.1f.pop 2 1 roll out 1 sub br.0b.dup 1: print def` 

Everything between macro and def is the identifier????  Or I know the # is like // in C right? Hmm....

Yeah, I am going to have to do more research about this. 
So is this language is loosely based on assembly in a sense?
Assembly might be a little over my head at the moment. Thank you for the explanation, I will look more into it all and see what turns up. For now, compiling the scripts seems to be my best route.

**Comment by sl236** [comment]
The identifier is the thing immediately preceding the keyword "def"; in this case, "print". Whenever `print` occurs later in the program, it is replaced with the body of the macro, i.e. in this case the text `dup 0: bz.1f.pop 2 1 roll out 1 sub br.0b.dup 1:` - just the same way macros work in other languages.

**Comment by sl236** [comment]
If you are new to programming, I strongly suggest you have a play with some real, non-esoteric languages and maybe a real, non-esoteric assembler!

**Comment by novusabeo** [comment]
Not new to programming really at all, but new to assemblers and obviously pretty new to piet and this assembler/compiler/interpreter.

I noticed something I was curious about -- when I assemble Fizzbuzz.piet and create a png I get a different image than when I compile Fizzbuzz.script and create a png. I realize these are different systems but is this because two different images can produce the same program in Piet or because I've done something wrong and need to kill some bugs.

**Comment by sl236** [comment]
Hi,

fizzbuzz.piet is handwritten assembly.

fizzbuzz.script is a higher level language which is first compiled to
assembly language before that is assembled. As with any compiled language,
this is generally going to produce less efficient output than writing the
assembly by hand; it is the price you pay for not having to write assembly
by hand. Compare the output of ./piet-compiler fizzbuzz.script to the
contents of fizzbuzz.piet.

You can see this happening in the real world too. https://godbolt.org/ is
a website that lets you write C++ functions and view the disassembly of
the code different compilers generate with different settings. Have a
play! Unlike the toy piet compiler in this repository, real compilers
perform extensive optimization work; even so, for complex functions the
output is often more verbose than what you might write by hand.

**Comment by novusabeo** [comment]
Definitely. Well, it's not bad for what it's worth. Does what it needs to do. 

Very cool, I'm going to give it a whirl. In a weird way, assembly in the scope of Piet looks simpler but requires a different understanding. Definitely want to understand more about it. Is there any documentation regarding the assembly level aside from the doc on the mainsites and on here? I think if it was more at hand I could work on something really cool with it perhaps. Otherwise, going to stick to setting it up with scripts for now.

**Comment by novusabeo** [comment]
Also, now that I'm looking at god bolt.org, I think I already have a better understanding. So in a way, Piet isn't really all that esoteric as it's based on fairly common assembly code. But it becomes esoteric at some point because the basic assembly is translated into an image or interprets an image somehow using a higher level system? Or using assembly?

I am mostly curious how it reads colors. 
I think it would be really cool to be able to expand Piet to encompass many more colors and possibly more commands or maybe expand it more to a higher-level language in this way. Because being able to code something a little more complex more easily using color/hue is just cool.

Also I know the colors aren't important, just the changes in hue or darkness are -- so implementing many more colors wouldn't be that difficult? I am wondering how difficult it would be to make Piet work with 256 colors.

**Comment by sl236** [comment]
The definitive documentation for Piet is on David Morgan Mar's site, here: http://www.dangermouse.net/esoteric/piet.html 

I believe he originally intended for people to create programs by hand in image editors, taking into account how the image looks as well as what the program does; you can see most of the samples on his site are artistic, and the ones produced with a code generator really stand out in their meaninglessness as images. 

I wrote the assembler and compiler as a toy project mainly to make it feasible to write the text adventure in the samples directory - encoding that amount of string data by hand would have been miserable! - as part of a puzzle for a puzzle contest I was involved with a few years back. I stole the opcode names for the assembly language from DMM's specification, but made up the rest of the syntax myself, so there's no docs on that other than what is here - but there's also not much syntax other than the opcodes described on DMM's page either :)

**Comment by sl236** [comment]
(You can see on DMM's site that other people have also written code generators, and also tools to help create programs by editing images directly).

**Comment by novusabeo** [comment]
Yeah, I've checked out all the other tools and landed here mainly because this is the only tool I was able (somewhat painstakingly for some reason) to get working and that allows you to write code and compile. MacOS is different ha.

Would be cool if you wrote something up on syntax?

I am mostly curious how it reads colors.
I think it would be really cool to be able to expand Piet to encompass many more colors and possibly more commands or maybe expand it more to a higher-level language in this way. Because being able to code something a little more complex more easily using color/hue is just cool.

Also I know the colors aren't important, just the changes in hue or darkness are -- so implementing many more colors wouldn't be that difficult? I am wondering how difficult it would be to make Piet work with 256 colors.

**Comment by sl236** [comment]
The actual running of the program in the image isn't done by any of my tools; if you're using the example command lines from the readme in this repo, then as the readme mentions it's done by Marc Majcher's Piet interpreter, forked from http://www.majcher.com/code/piet/Piet-Interpreter.html and with a couple of minor bugs fixed; though you could equally use any of the other interpreters linked from DMM's site. Have a look at https://github.com/sl236/Piet/blob/master/interpreter/PietInterpreter.pm - although it is Perl, it is quite readable.

**Comment by sl236** [comment]
Oh, if you're interested in image-based esoteric systems where specific colours, rather than colour changes, mean things, you might like to check out wireworld: https://en.wikipedia.org/wiki/Wireworld - people have done some awesome things in that: https://www.quinapalus.com/wi-index.html

**Comment by novusabeo** [comment]
Will do, thank you. Is it possible there are different interpreters? I was using https://gabriellesc.github.io/piet/index.html with an image I got from the ./compiler .script | ./assembler   loaded in and it wasn't giving me the anticipated output. 

Possible the pnm to png converter I used wasn't right or something too I suppose. But it seemed to be interpreting and debugging fine until it stopped and didn't move into the tracks at all.

And Whoa, Wireworld looks awesome. I do like the Piet non-specific color change setup for it's simplicity but really. I mean really you don't need too complex a system to build much more on top of it. But I'll check this all out. Basically I'm really interested in the idea that Piet can represent a relatively complicated program in a simple and easily reversible format. I think it could have some really incredible applications and still be really interesting ha

**Comment by sl236** [comment]
Hmm, it looks like that interpreter is broken; execution does not traverse white pixels, so any Piet images that rely on that don't work. This includes several samples on DMM's page ( e.g. Sylvain Tintillier's prime number generator), and the output of the tools in this repo.

**Comment by novusabeo** [comment]
Oh, I see. Well it's really nice wish it was working. This one seems to traverse better though it doesn't handle the format the compiler here seems to produce very well. https://www.rapapaing.com/blog/pietdev/
